# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e188e3556be62b0128d3c671cc9c496bd5aa0ca58c4e341295dd32c1ea0e5e7ae0b57ca2afa47122f9b86316cd6110feab2db7147c69a7ac6073d3a49fa0ec6

test:
  secret_key_base: 000e3dbb0962856588ec2e6e374b6f91de3c741edc8a43cf133270a78af1c94b699b75838b6cb4ff43db9d09c55c8f72247f2062d879faca797323c816adbfab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
